"""Create the immutable 124-episode formal LeRobot dataset.

The builder concatenates the 84 human demonstrations and the 40 reviewed HIL
episodes without mutating either source. It writes a unified episode manifest
used by both training lines; the phase-aware line only adds a fixed frame-loss
sidecar generated by :mod:`radeon_oneloop.phase_targets`.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .contracts import ACTION_NAMES, CAMERA_KEYS, FPS, require_action_names


DATA_FILE = Path("data/chunk-000/file-000.parquet")
EPISODES_FILE = Path("meta/episodes/chunk-000/file-000.parquet")
TASKS_FILE = Path("meta/tasks.parquet")
INFO_FILE = Path("meta/info.json")
STATS_FILE = Path("meta/stats.json")
INTERVENTION_KEY = "complementary_info.is_intervention"


@dataclass(frozen=True)
class Source:
    name: str
    root: Path
    kind: str
    manifest: Path | None = None


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows = []
    with path.open(encoding="utf-8") as handle:
        for line_no, line in enumerate(handle, 1):
            if line.strip():
                try:
                    rows.append(json.loads(line))
                except json.JSONDecodeError as exc:
                    raise ValueError(f"invalid JSON at {path}:{line_no}") from exc
    return rows


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, sort_keys=True) + "\n")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(4 * 1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def validate_source(source: Source) -> tuple[dict[str, Any], Any, Any]:
    try:
        import pandas as pd
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError("pandas and pyarrow are required; install radeon-oneloop[data]") from exc
    missing = [path for path in (INFO_FILE, STATS_FILE, DATA_FILE, EPISODES_FILE, TASKS_FILE) if not (source.root / path).is_file()]
    if missing:
        raise FileNotFoundError(f"{source.name} is missing: {missing}")
    info = read_json(source.root / INFO_FILE)
    if int(info["fps"]) != FPS:
        raise ValueError(f"{source.name}: fps must be {FPS}")
    require_action_names(info["features"]["action"]["names"])
    require_action_names(info["features"]["observation.state"]["names"])
    for camera in CAMERA_KEYS:
        feature = info["features"].get(camera)
        if not feature or feature.get("shape") != [480, 640, 3]:
            raise ValueError(f"{source.name}: invalid camera feature {camera}")
    data = pd.read_parquet(source.root / DATA_FILE)
    episodes = pd.read_parquet(source.root / EPISODES_FILE)
    if len(data) != int(info["total_frames"]):
        raise ValueError(f"{source.name}: frame count mismatch")
    if episodes["episode_index"].nunique() != int(info["total_episodes"]):
        raise ValueError(f"{source.name}: episode count mismatch")
    if sorted(int(value) for value in episodes["episode_index"].unique()) != list(range(len(episodes))):
        raise ValueError(f"{source.name}: episode indices must be contiguous from zero")
    return info, data, episodes


def _numeric_stats(frame: Any, columns: list[str]) -> dict[str, Any]:
    import numpy as np

    result: dict[str, Any] = {}
    for column in columns:
        first = frame[column].iloc[0]
        values = np.stack(frame[column].to_numpy()) if hasattr(first, "shape") and getattr(first, "shape", ()) else frame[column].to_numpy()
        values = values.astype(float)
        result[column] = {
            "min": np.atleast_1d(np.nanmin(values, axis=0)).tolist(),
            "max": np.atleast_1d(np.nanmax(values, axis=0)).tolist(),
            "mean": np.atleast_1d(np.nanmean(values, axis=0)).tolist(),
            "std": np.atleast_1d(np.nanstd(values, axis=0)).tolist(),
            "count": [float(len(frame))],
        }
    return result


def _combine_video_stats(source_stats: list[dict[str, Any]]) -> dict[str, Any]:
    import numpy as np

    result: dict[str, Any] = {}
    for key in CAMERA_KEYS:
        items = [stats[key] for stats in source_stats if key in stats]
        if len(items) != len(source_stats):
            raise ValueError(f"missing video statistics for {key}")
        counts = np.asarray([float(item.get("count", [0])[0]) for item in items])
        total = float(counts.sum())
        means = [np.asarray(item["mean"], dtype=float) for item in items]
        mean = sum(value * count for value, count in zip(means, counts, strict=True)) / total
        variance = sum(
            count * (np.asarray(item["std"], dtype=float) ** 2 + (item_mean - mean) ** 2)
            for item, item_mean, count in zip(items, means, counts, strict=True)
        ) / total
        result[key] = {
            "min": np.minimum.reduce([np.asarray(item["min"], dtype=float) for item in items]).tolist(),
            "max": np.maximum.reduce([np.asarray(item["max"], dtype=float) for item in items]).tolist(),
            "mean": mean.tolist(),
            "std": np.sqrt(variance).tolist(),
            "count": [total],
        }
    return result


def _copy_videos(source: Source, output: Path, episodes: Any, file_offsets: dict[str, int]) -> Any:
    episodes = episodes.copy()
    for key in CAMERA_KEYS:
        file_column = f"videos/{key}/file_index"
        chunk_column = f"videos/{key}/chunk_index"
        if file_column not in episodes.columns or chunk_column not in episodes.columns:
            raise ValueError(f"{source.name}: missing video location columns for {key}")
        pairs = episodes[[chunk_column, file_column]].drop_duplicates()
        mapping: dict[tuple[int, int], tuple[int, int]] = {}
        for _, pair in pairs.iterrows():
            old_chunk, old_file = int(pair[chunk_column]), int(pair[file_column])
            new_file = old_file + file_offsets[key]
            mapping[(old_chunk, old_file)] = (0, new_file)
            src = source.root / "videos" / key / f"chunk-{old_chunk:03d}" / f"file-{old_file:03d}.mp4"
            dst = output / "videos" / key / "chunk-000" / f"file-{new_file:03d}.mp4"
            if not src.is_file():
                raise FileNotFoundError(src)
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
        for row_index in episodes.index:
            pair = (int(episodes.at[row_index, chunk_column]), int(episodes.at[row_index, file_column]))
            new_chunk, new_file = mapping[pair]
            episodes.at[row_index, chunk_column] = new_chunk
            episodes.at[row_index, file_column] = new_file
        file_offsets[key] += len(pairs)
    return episodes


def _source_manifest(source: Source, episodes: Any, episode_offset: int, frame_offset: int) -> list[dict[str, Any]]:
    by_episode = {int(row["episode_index"]): row for _, row in episodes.iterrows()}
    if source.kind == "bc_seed":
        rows = []
        for old_index in sorted(by_episode):
            ep = by_episode[old_index]
            length = int(ep["dataset_to_index"] - ep["dataset_from_index"])
            rows.append(
                {
                    "episode_index": old_index + episode_offset,
                    "source_episode_index": old_index,
                    "source_name": source.name,
                    "source_kind": "bc_seed",
                    "episode_id": f"episode_{old_index + episode_offset:06d}",
                    "dataset_from_index": int(ep["dataset_from_index"]) + frame_offset,
                    "dataset_to_index": int(ep["dataset_to_index"]) + frame_offset,
                    "length": length,
                    "handover_success": True,
                    "failure_type": "success",
                    "segments": {},
                }
            )
        return rows
    if source.manifest is None:
        raise ValueError(f"{source.name}: HIL source requires --hil-manifest")
    rows = read_jsonl(source.manifest)
    if {int(row["episode_index"]) for row in rows} != set(by_episode):
        raise ValueError(f"{source.name}: HIL manifest does not cover exactly every source episode")
    output = []
    for row in rows:
        new = json.loads(json.dumps(row))
        old_index = int(row["episode_index"])
        new_index = old_index + episode_offset
        new["source_episode_index"] = old_index
        new["source_name"] = source.name
        new["source_kind"] = "hil"
        new["episode_index"] = new_index
        new["episode_id"] = f"episode_{new_index:06d}"
        for field in ("dataset_from_index", "dataset_to_index"):
            if new.get(field) is not None:
                new[field] = int(new[field]) + frame_offset
        output.append(new)
    return output


def build(*, sources: list[Source], output: Path, overwrite: bool = False) -> dict[str, Any]:
    try:
        import numpy as np
        import pandas as pd
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError("numpy, pandas and pyarrow are required") from exc
    if output.exists():
        if not overwrite:
            raise FileExistsError(f"output already exists: {output}")
        shutil.rmtree(output)
    output.mkdir(parents=True)

    validated = [(source, *validate_source(source)) for source in sources]
    base_info = json.loads(json.dumps(validated[0][1]))
    task_hashes = {sha256(source.root / TASKS_FILE) for source, *_ in validated}
    if len(task_hashes) != 1:
        raise ValueError("source task tables are not byte-identical")
    (output / "meta").mkdir(parents=True, exist_ok=True)
    shutil.copy2(sources[0].root / TASKS_FILE, output / TASKS_FILE)

    data_parts = []
    episode_parts = []
    manifest_rows: list[dict[str, Any]] = []
    episode_offset = 0
    frame_offset = 0
    file_offsets = {key: 0 for key in CAMERA_KEYS}
    source_reports = []
    for source, info, data, episodes in validated:
        data = data.copy()
        if INTERVENTION_KEY not in data.columns:
            data[INTERVENTION_KEY] = np.zeros(len(data), dtype=np.float32)
        data["index"] = data["index"].astype(int) + frame_offset
        data["episode_index"] = data["episode_index"].astype(int) + episode_offset
        data_parts.append(data)

        source_manifest = _source_manifest(source, episodes, episode_offset, frame_offset)
        manifest_rows.extend(source_manifest)
        episodes = _copy_videos(source, output, episodes, file_offsets)
        episodes["episode_index"] = episodes["episode_index"].astype(int) + episode_offset
        episodes["dataset_from_index"] = episodes["dataset_from_index"].astype(int) + frame_offset
        episodes["dataset_to_index"] = episodes["dataset_to_index"].astype(int) + frame_offset
        episode_parts.append(episodes)
        source_reports.append(
            {
                "name": source.name,
                "kind": source.kind,
                "episodes": int(info["total_episodes"]),
                "frames": int(info["total_frames"]),
                "info_sha256": sha256(source.root / INFO_FILE),
                "data_sha256": sha256(source.root / DATA_FILE),
                "manifest_sha256": sha256(source.manifest) if source.manifest else None,
            }
        )
        episode_offset += int(info["total_episodes"])
        frame_offset += int(info["total_frames"])

    combined_data = pd.concat(data_parts, ignore_index=True, sort=False)
    combined_episodes = pd.concat(episode_parts, ignore_index=True, sort=False)
    (output / DATA_FILE).parent.mkdir(parents=True, exist_ok=True)
    (output / EPISODES_FILE).parent.mkdir(parents=True, exist_ok=True)
    combined_data.to_parquet(output / DATA_FILE, index=False)
    combined_episodes.to_parquet(output / EPISODES_FILE, index=False)

    base_info["total_episodes"] = episode_offset
    base_info["total_frames"] = frame_offset
    base_info["splits"] = {"train": f"0:{episode_offset}"}
    base_info["features"][INTERVENTION_KEY] = {"dtype": "float32", "shape": [1], "names": None}
    write_json(output / INFO_FILE, base_info)

    numeric_columns = [
        "action",
        "observation.state",
        "timestamp",
        "frame_index",
        "episode_index",
        "index",
        "task_index",
        INTERVENTION_KEY,
    ]
    stats = _numeric_stats(combined_data, numeric_columns)
    stats.update(_combine_video_stats([read_json(source.root / STATS_FILE) for source in sources]))
    write_json(output / STATS_FILE, stats)
    manifest_path = output / "oneloop" / "episode_manifest.jsonl"
    write_jsonl(manifest_path, manifest_rows)

    hash_files = sorted(path for path in output.rglob("*") if path.is_file())
    hash_lines = [f"{sha256(path)}  {path.relative_to(output)}" for path in hash_files]
    hashes_path = output / "oneloop" / "hashes.sha256"
    hashes_path.write_text("\n".join(hash_lines) + "\n", encoding="utf-8")
    dataset_hash = hashlib.sha256(hashes_path.read_bytes()).hexdigest()
    report = {
        "schema_version": "radeon_oneloop.formal_dataset.v1",
        "repo_id": "phi-media-lab/radeon-oneloop-formal-handover-v1",
        "dataset_hash": dataset_hash,
        "episodes": episode_offset,
        "frames": frame_offset,
        "fps": FPS,
        "action_names": list(ACTION_NAMES),
        "camera_keys": list(CAMERA_KEYS),
        "intervention_frames": int(combined_data[INTERVENTION_KEY].sum()),
        "sources": source_reports,
        "artifacts": {
            "info": str(INFO_FILE),
            "data": str(DATA_FILE),
            "episodes": str(EPISODES_FILE),
            "manifest": str(manifest_path.relative_to(output)),
            "hashes": str(hashes_path.relative_to(output)),
        },
    }
    write_json(output / "oneloop" / "dataset_report.json", report)
    return report


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bc-root", type=Path, required=True)
    parser.add_argument("--hil-root", type=Path, required=True)
    parser.add_argument("--hil-manifest", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()
    report = build(
        sources=[
            Source("bc_seed_handover_v1", args.bc_root.resolve(), "bc_seed"),
            Source("hil_rlready_batch1_batch2", args.hil_root.resolve(), "hil", args.hil_manifest.resolve()),
        ],
        output=args.output.resolve(),
        overwrite=args.overwrite,
    )
    print(json.dumps(report, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()

