#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 4 ]]; then
  printf 'usage: %s LEFT_PORT RIGHT_PORT LEFT_CALIBRATION_ID RIGHT_CALIBRATION_ID\n' "$0" >&2
  exit 64
fi

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
: "${ONELOOP_OBSERVED_CORE_ROOT:?set ONELOOP_OBSERVED_CORE_ROOT to the exact hash-verified formal asset}"

export ONELOOP_LIVE_DURATION_S=${ONELOOP_LIVE_DURATION_S:-120}
export ONELOOP_LIVE_TIMEOUT_S=${ONELOOP_LIVE_TIMEOUT_S:-300}
export ONELOOP_RENDER_HZ=${ONELOOP_RENDER_HZ:-8}
export ONELOOP_SHOW_PRESENTER=${ONELOOP_SHOW_PRESENTER:-1}
export ONELOOP_SHOW_GENESIS_VIEWER=${ONELOOP_SHOW_GENESIS_VIEWER:-0}
export ONELOOP_RECORD_VIDEO=1
export ONELOOP_LIVE_CANDIDATE_NONFORMAL=0
export ONELOOP_GENERATED_FILL_ENABLED=0
export ONELOOP_FINAL_TASK_RECORDING=1
export ONELOOP_FAULT_EXIT_AFTER_FRAMES=0

exec "$repo_root/ops/run_amd_decoupled_gaussian_live_gate.sh" "$@"
